Bag of words and TF-IDF are the techniques use for feature extraction from text documents. Bag of words is a simple technique which converts text into a vector of numbers. It ignores grammar and order of words. TF-IDF is a weighted model commonly used for information retrieval problems. 

TF-IDF is a statistical measure that evaluates how relevant a word is to a document in a collection of documents. This is done by multiplying two metrics: how many times a word appears in a document, and the inverse document frequency of the word across a set of documents. TF-IDF is used for text classification and text clustering.

Corpus: A collection of text documents is called corpus. The plural form of corpus is corpora.

vocabularies: A vocabulary is a set of words known to a particular person, class, etc. or found in a particular text.

document: A document is a piece of text that may be classified in some category.

word: A word is a string of characters.

In [1]:
import pandas as pd
import numpy as np


In [2]:
df = pd.read_csv('IMDB Dataset.csv')
df.head()

review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [24]:
doc1 = df['review'][0:100]

In [25]:
#bag of words
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()

df2 = cv.fit_transform(doc1)

In [26]:
df2.shape

(100, 4755)

In [27]:
print(cv.vocabulary_)

{'one': 2924, 'of': 2898, 'the': 4189, 'other': 2953, 'reviewers': 3501, 'has': 1882, 'mentioned': 2623, 'that': 4186, 'after': 134, 'watching': 4578, 'just': 2268, 'oz': 2984, 'episode': 1384, 'you': 4736, 'll': 2456, 'be': 402, 'hooked': 1989, 'they': 4205, 'are': 271, 'right': 3520, 'as': 297, 'this': 4215, 'is': 2199, 'exactly': 1421, 'what': 4611, 'happened': 1867, 'with': 4657, 'me': 2592, 'br': 545, 'first': 1576, 'thing': 4208, 'struck': 4013, 'about': 59, 'was': 4570, 'its': 2210, 'brutality': 588, 'and': 218, 'unflinching': 4411, 'scenes': 3629, 'violence': 4518, 'which': 4621, 'set': 3704, 'in': 2089, 'from': 1662, 'word': 4679, 'go': 1755, 'trust': 4355, 'not': 2856, 'show': 3757, 'for': 1618, 'faint': 1487, 'hearted': 1907, 'or': 2939, 'timid': 4254, 'pulls': 3273, 'no': 2835, 'punches': 3276, 'regards': 3398, 'to': 4262, 'drugs': 1255, 'sex': 3711, 'hardcore': 1874, 'classic': 768, 'use': 4460, 'it': 2206, 'called': 631, 'nickname': 2824, 'given': 1736, 'oswald': 2951, 'm

In [7]:
print(df2.toarray())

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 1 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 2 ... 0 0 0]]


In [11]:
cv.transform(['This is a good movie']).toarray()

array([[0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [8]:
df.head(100)

review sentiment
0   One of the other reviewers has mentioned that ...  positive
1   A wonderful little production. <br /><br />The...  positive
2   I thought this was a wonderful way to spend ti...  positive
3   Basically there's a family where a little boy ...  negative
4   Petter Mattei's "Love in the Time of Money" is...  positive
..                                                ...       ...
95  Daniel Day-Lewis is the most versatile actor a...  positive
96  My guess would be this was originally going to...  negative
97  Well, I like to watch bad horror B-Movies, cau...  negative
98  This IS the worst movie I have ever seen, as w...  negative
99  I have been a Mario fan for as long as I can r...  positive

[100 rows x 2 columns]

In [10]:
cv.transform(['good movie']).toarray()

array([[0, 0, 0, ..., 0, 0, 0]], dtype=int64)

# Ngrams

In [31]:
doc2 = df['review'][100:200]

In [34]:
doc2.head()

100    This short film that inspired the soon-to-be f...
101    Okay, last night, August 18th, 2004, I had the...
102    I bought this game on an impulse buy from walm...
103    No, this hilariously horrible 70's made-for-TV...
104    It is easy to tell early in this movie exactly...
Name: review, dtype: object

In [35]:
doc2.shape

(100,)

In [39]:
#cheack the average length of the reviews
df['review'].str.len().mean()


1309.43102

In [43]:
#ngram
cv = CountVectorizer(ngram_range=(100 ,100))
cv.fit_transform(doc2)

<100x14017 sparse matrix of type '<class 'numpy.int64'>'
	with 14017 stored elements in Compressed Sparse Row format>

In [42]:
print(cv.vocabulary_)

Exception in callback BaseAsyncIOLoop._handle_events(516, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(516, 1)>
Traceback (most recent call last):
  File "c:\Users\Haseeb\anaconda3\envs\machine_learning\Lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "c:\Users\Haseeb\anaconda3\envs\machine_learning\Lib\site-packages\tornado\platform\asyncio.py", line 206, in _handle_events
    handler_func(fileobj, events)
  File "c:\Users\Haseeb\anaconda3\envs\machine_learning\Lib\site-packages\zmq\eventloop\zmqstream.py", line 634, in _handle_events
    self._handle_recv()
  File "c:\Users\Haseeb\anaconda3\envs\machine_learning\Lib\site-packages\zmq\eventloop\zmqstream.py", line 663, in _handle_recv
    self._run_callback(callback, msg)
  File "c:\Users\Haseeb\anaconda3\envs\machine_learning\Lib\site-packages\zmq\eventloop\zmqstream.py", line 584, in _run_callback
    f = callback(*args, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Use

# TFIDF: Term Frequency - Inverse Document Frequency

In [45]:
doc3 = df['review'][200:300]
doc3.head()

200    Interesting and short television movie describ...
201    Any film about WWII made during WWII by a Brit...
202    A brilliant horror film. Utterly gruesome and ...
203    I absolutely love this film. Everything about ...
204    No one can say I wasn't warned as I have read ...
Name: review, dtype: object

In [46]:
doc3.shape

(100,)

In [49]:
#tfidf
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf = TfidfVectorizer()
df3 = tfidf.fit_transform(doc3).toarray()


In [50]:
df3

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [48]:
print(tfidf.vocabulary_)

{'interesting': 2099, 'and': 181, 'short': 3549, 'television': 3953, 'movie': 2610, 'describes': 1057, 'some': 3675, 'of': 2752, 'the': 3977, 'machinations': 2397, 'surrounding': 3885, 'jay': 2147, 'leno': 2296, 'replacing': 3275, 'carson': 590, 'as': 254, 'host': 1943, 'tonight': 4063, 'show': 3558, 'film': 1506, 'is': 2126, 'currently': 943, 'very': 4256, 'topical': 4069, 'given': 1691, 'public': 3103, 'drama': 1185, 'conan': 800, 'brien': 492, 'br': 471, 'does': 1156, 'good': 1719, 'job': 2154, 'sparking': 3704, 'viewers': 4269, 'interest': 2097, 'in': 2021, 'events': 1348, 'showing': 3561, 'concerns': 805, 'stakeholders': 3745, 'particularly': 2875, 'nbc': 2658, 'executives': 1375, 'portrayal': 3002, 'ovitz': 2835, 'was': 4326, 'compelling': 787, 'thought': 4013, 'still': 3784, 'many': 2436, 'characters': 644, 'were': 4362, 'only': 2776, 'briefly': 491, 'limned': 2328, 'or': 2790, 'touched': 4079, 'upon': 4224, 'acting': 75, 'seemed': 3476, 'perfunctory': 2914, 'nevertheless': 2678

In [51]:
print(tfidf.idf_)

[4.92197334 3.53567898 4.51650823 ... 4.51650823 4.92197334 4.92197334]
